version: '2'
services:
    perl:
        image: kanfushihara/perl-carton:5.30.1
        volumes:
            - ./:/app
            - perl-local:/app/local
        tty: true
volumes:
  perl-local:
    driver: local
